#################
# Site settings #
#################

title: "#cmdline.org"
baseurl: ""
url: "https://cmdline.org"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


##################
# Build settings #
##################

markdown: kramdown
exclude: ["README.md"]

kramdown:
  auto_ids: false
